language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# Start PostgreSQL
services:
  - postgresql
before_script:
  - psql < polls/sql/init_db.sql -U postgres
  - psq -d polls < polls/sql/create_tables.sql -U postgres
# command to run tests
script: pytest
