# FS
fs_script_path: "/modules/backupers/fs/fs.sh"
fs_source: "/home/pad /tmp"
fs_dst: "/backup_fs"
fs_exclude: "0"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  database: "polls"